# UTS Logptog kelompok 12

# -*- coding: utf-8 -*-
"""uts bagian 1: reza

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1290Osnl7oxuOGWreQKnvV9wqoaX2E-xU
"""

import sqlite3
from datetime import datetime


def buat_database():
    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Users ( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT,
            password TEXT, role TEXT) """)

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Produk ( id INTEGER PRIMARY KEY AUTOINCREMENT, nama_produk TEXT,
            harga_modal INTEGER, harga_jual INTEGER, stok INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            tanggal TEXT, total_bayar INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Detail_Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            id_transaksi INTEGER, id_produk INTEGER, jumlah INTEGER, subtotal INTEGER)""")

    cursor.execute("SELECT COUNT(*) FROM Users")
    if cursor.fetchone()[0] == 0:
        users = [("SYAHREZA", "EjaAdmin", "Admin"), ("FIRAAS", "FiraasKasir", "Kasir")]

        cursor.executemany(""" INSERT INTO Users (username, password, role) VALUES (?, ?, ?) """, users)

    cursor.execute("SELECT COUNT(*) FROM Produk")
    if cursor.fetchone()[0] == 0:
        produk =[('Telor ayam 1kg', 27000, 30000, 15), ('Gas melon 3kg', 20000, 24000, 15), ('Minyak nyawit 1L', 16000, 22000, 25),
            ('Air mineral 600ml', 2000, 4000, 55), ('Kopi item sachet', 1500, 2000, 40), ('Sabun batang', 3000, 5000, 20),
            ('Mie Goreng', 2500, 3500, 25), ('Dubai chewy cookie', 8000, 12000, 15), ('Salt bread cheese', 18000, 22000, 15),
            ('Minyak kayu putih 60ml', 12000, 16000, 10)]

        cursor.executemany(""" INSERT INTO Produk (nama_produk, harga_modal, harga_jual, stok) VALUES (?, ?, ?, ?) """, produk)

    conn.commit()
    conn.close()

def menu_admin():
    while True:
        print("\n=== MENU ADMIN ===")
        print("1. Kelola Produk")
        print("2. Melihat Transaksi")
        print("3. Laporan Penjualan")
        print("4. Hapus Produk")
        print("5. Logout")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            print("Fitur Kelola Produk akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "2":
            print("Fitur Melihat Transaksi akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "3":
            print("Fitur Laporan Penjualan akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "4":
            print("Fitur Hapus Produk akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "5":
            print("Logout berhasil.")
            break
        else:
            print("Pilihan tidak tersedia.")


def menu_kasir():
    while True:
        print("\n=== MENU KASIR ===")
        print("1. Transaksi Penjualan")
        print("2. Lihat Produk")
        print("3. Logout")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            print("Fitur Transaksi akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "2":
            print("Fitur Lihat Produk akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "3":
            print("Logout berhasil.")
            break
        else:
            print("Pilihan tidak tersedia.")


def login():
    print("\n================================")
    print("       SMART-RETAIL LOGIN")
    print("================================")

    username = input("Username: ")
    password = input("Password: ")

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    cursor.execute(
        "SELECT username, role FROM Users WHERE username = ? AND password = ?",
        (username, password)
    )
    user = cursor.fetchone()

    conn.close()

    if user:
        print(f"\nLogin berhasil. Selamat datang, {user[0]}!")

        if user[1] == "Admin":
            menu_admin()
        elif user[1] == "Kasir":
            menu_kasir()
    else:
        print("\nUsername atau password salah.")


login()

