# UTS Logptog kelompok 12

# -*- coding: utf-8 -*-
"""uts bagian 1: reza

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1290Osnl7oxuOGWreQKnvV9wqoaX2E-xU
"""

import sqlite3
from datetime import datetime


def buat_database():
    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Users ( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT,
            password TEXT, role TEXT) """)

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Produk ( id INTEGER PRIMARY KEY AUTOINCREMENT, nama_produk TEXT,
            harga_modal INTEGER, harga_jual INTEGER, stok INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            tanggal TEXT, total_bayar INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Detail_Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            id_transaksi INTEGER, id_produk INTEGER, jumlah INTEGER, subtotal INTEGER)""")

    cursor.execute("SELECT COUNT(*) FROM Users")
    if cursor.fetchone()[0] == 0:
        users = [("SYAHREZA", "EjaAdmin", "Admin"), ("FIRAAS", "FiraasKasir", "Kasir")]

        cursor.executemany(""" INSERT INTO Users (username, password, role) VALUES (?, ?, ?) """, users)

    cursor.execute("SELECT COUNT(*) FROM Produk")
    if cursor.fetchone()[0] == 0:
        produk =[('Telor ayam 1kg', 27000, 30000, 15), ('Gas melon 3kg', 20000, 24000, 15), ('Minyak nyawit 1L', 16000, 22000, 25),
            ('Air mineral 600ml', 2000, 4000, 55), ('Kopi item sachet', 1500, 2000, 40), ('Sabun batang', 3000, 5000, 20),
            ('Mie Goreng', 2500, 3500, 25), ('Dubai chewy cookie', 8000, 12000, 15), ('Salt bread cheese', 18000, 22000, 15),
            ('Minyak kayu putih 60ml', 12000, 16000, 10)]

        cursor.executemany(""" INSERT INTO Produk (nama_produk, harga_modal, harga_jual, stok) VALUES (?, ?, ?, ?) """, produk)

    conn.commit()
    conn.close()

def lihat_produk():
    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()
    cursor.execute("SELECT id, nama_produk, harga_modal, harga_jual, stok FROM Produk ORDER BY id")
    data = cursor.fetchall()

    print("\n=== DATA PRODUK ===")
    for produk in data:
        print(f"ID: {produk[0]} | {produk[1]} | Modal: {produk[2]} | Jual: {produk[3]} | Stok: {produk[4]}")
    conn.close()


def tambah_produk():
    print("\n=== TAMBAH PRODUK ===")
    nama = input("Nama produk: ")
    harga_modal = float(input("Harga modal: "))
    harga_jual = float(input("Harga jual: "))
    stok = int(input("Stok: "))

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO Produk (nama_produk, harga_modal, harga_jual, stok) VALUES (?, ?, ?, ?)",
        (nama, harga_modal, harga_jual, stok)
    )
    conn.commit()
    conn.close()
    print("Produk berhasil ditambahkan.")


def ubah_produk():
    lihat_produk()
    try:
        id_produk = int(input("Masukkan ID produk yang ingin diubah: "))
    except ValueError:
        print("ID harus berupa angka.")
        return

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM Produk WHERE id = ?", (id_produk,))
    produk = cursor.fetchone()

    if not produk:
        print("Produk tidak ditemukan.")
        conn.close()
        return

    nama = input(f"Nama produk [{produk[1]}]: ") or produk[1]
    harga_modal = input(f"Harga modal [{produk[2]}]: ")
    harga_jual = input(f"Harga jual [{produk[3]}]: ")
    stok = input(f"Stok [{produk[4]}]: ")

    harga_modal = float(harga_modal) if harga_modal else produk[2]
    harga_jual = float(harga_jual) if harga_jual else produk[3]
    stok = int(stok) if stok else produk[4]

    cursor.execute(
        "UPDATE Produk SET nama_produk=?, harga_modal=?, harga_jual=?, stok=? WHERE id=?",
        (nama, harga_modal, harga_jual, stok, id_produk)
    )
    conn.commit()
    conn.close()
    print("Produk berhasil diubah.")


def restock_produk():
    lihat_produk()
    try:
        id_produk = int(input("Masukkan ID produk: "))
        jumlah = int(input("Jumlah restock: "))
    except ValueError:
        print("Input harus berupa angka.")
        return

    if jumlah <= 0:
        print("Jumlah restock harus lebih dari 0.")
        return

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()
    cursor.execute("SELECT nama_produk FROM Produk WHERE id = ?", (id_produk,))
    produk = cursor.fetchone()

    if not produk:
        print("Produk tidak ditemukan.")
    else:
        cursor.execute("UPDATE Produk SET stok = stok + ? WHERE id = ?", (jumlah, id_produk))
        conn.commit()
        print(f"Stok {produk[0]} berhasil ditambah {jumlah}.")
    conn.close()


def hapus_produk():
    lihat_produk()
    try:
        id_produk = int(input("Masukkan ID produk yang ingin dihapus: "))
    except ValueError:
        print("ID harus berupa angka.")
        return

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()
    cursor.execute("SELECT nama_produk FROM Produk WHERE id = ?", (id_produk,))
    produk = cursor.fetchone()

    if not produk:
        print("Produk tidak ditemukan.")
    else:
        konfirmasi = input(f"Hapus {produk[0]}? (y/n): ").lower()
        if konfirmasi == "y":
            cursor.execute("DELETE FROM Produk WHERE id = ?", (id_produk,))
            conn.commit()
            print("Produk berhasil dihapus.")
        else:
            print("Penghapusan dibatalkan.")
    conn.close()


def cari_produk():
    keyword = input("Masukkan ID atau nama produk: ").strip()

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    if keyword.isdigit():
        cursor.execute("SELECT id, nama_produk, harga_jual, stok FROM Produk WHERE id = ?", (int(keyword),))
    else:
        cursor.execute("SELECT id, nama_produk, harga_jual, stok FROM Produk WHERE nama_produk LIKE ?", (f"%{keyword}%",))

    data = cursor.fetchall()

    if data:
        for produk in data:
            print(f"ID: {produk[0]} | {produk[1]} | Harga: {produk[2]} | Stok: {produk[3]}")
    else:
        print("Produk tidak ditemukan.")
    conn.close()


def kelola_produk():
    while True:
        print("\n=== KELOLA PRODUK ===")
        print("1. Lihat Produk")
        print("2. Tambah Produk")
        print("3. Ubah Produk")
        print("4. Restock Barang")
        print("5. Cari Produk")
        print("6. Kembali")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            lihat_produk()
        elif pilihan == "2":
            tambah_produk()
        elif pilihan == "3":
            ubah_produk()
        elif pilihan == "4":
            restock_produk()
        elif pilihan == "5":
            cari_produk()
        elif pilihan == "6":
            break
        else:
            print("Pilihan tidak tersedia.")


def menu_admin():
    while True:
        print("\n=== MENU ADMIN ===")
        print("1. Kelola Produk")
        print("2. Melihat Transaksi")
        print("3. Laporan Penjualan")
        print("4. Hapus Produk")
        print("5. Logout")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            kelola_produk()
        elif pilihan == "2":
            print("Fitur Melihat Transaksi akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "3":
            print("Fitur Laporan Penjualan akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "4":
            hapus_produk()
        elif pilihan == "5":
            print("Logout berhasil.")
            break
        else:
            print("Pilihan tidak tersedia.")


def menu_kasir():
    while True:
        print("\n=== MENU KASIR ===")
        print("1. Transaksi Penjualan")
        print("2. Lihat Produk")
        print("3. Logout")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            print("Fitur Transaksi akan ditambahkan pada tahap berikutnya.")
        elif pilihan == "2":
            lihat_produk()
        elif pilihan == "3":
            print("Logout berhasil.")
            break
        else:
            print("Pilihan tidak tersedia.")



def login():
    print("\n================================")
    print("       SMART-RETAIL LOGIN")
    print("================================")

    username = input("Username: ")
    password = input("Password: ")

    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    cursor.execute(
        "SELECT username, role FROM Users WHERE username = ? AND password = ?",
        (username, password)
    )
    user = cursor.fetchone()

    conn.close()

    if user:
        print(f"\nLogin berhasil. Selamat datang, {user[0]}!")

        if user[1] == "Admin":
            menu_admin()
        elif user[1] == "Kasir":
            menu_kasir()
    else:
        print("\nUsername atau password salah.")


login()

