# -*- coding: utf-8 -*-
"""uts bagian 1: reza

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1290Osnl7oxuOGWreQKnvV9wqoaX2E-xU
"""

import sqlite3
from datetime import datetime


def buat_database():
    conn = sqlite3.connect("smart_retail.db")
    cursor = conn.cursor()

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Users ( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT,
            password TEXT, role TEXT) """)

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Produk ( id INTEGER PRIMARY KEY AUTOINCREMENT, nama_produk TEXT,
            harga_modal INTEGER, harga_jual INTEGER, stok INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            tanggal TEXT, total_bayar INTEGER )""")

    cursor.execute(""" CREATE TABLE IF NOT EXISTS Detail_Transaksi ( id INTEGER PRIMARY KEY AUTOINCREMENT,
            id_transaksi INTEGER, id_produk INTEGER, jumlah INTEGER, subtotal INTEGER)""")

    cursor.execute("SELECT COUNT(*) FROM Users")
    if cursor.fetchone()[0] == 0:
        users = [("SYAHREZA", "EjaAdmin", "Admin"), ("FIRAAS", "FiraasKasir", "Kasir")]

        cursor.executemany(""" INSERT INTO Users (username, password, role) VALUES (?, ?, ?) """, users)

    cursor.execute("SELECT COUNT(*) FROM Produk")
    if cursor.fetchone()[0] == 0:
        produk =[('Telor ayam 1kg', 27000, 30000, 15), ('Gas melon 3kg', 20000, 24000, 15), ('Minyak nyawit 1L', 16000, 22000, 25),
            ('Air mineral 600ml', 2000, 4000, 55), ('Kopi item sachet', 1500, 2000, 40), ('Sabun batang', 3000, 5000, 20),
            ('Mie Goreng', 2500, 3500, 25), ('Dubai chewy cookie', 8000, 12000, 15), ('Salt bread cheese', 18000, 22000, 15),
            ('Minyak kayu putih 60ml', 12000, 16000, 10)]

        cursor.executemany(""" INSERT INTO Produk (nama_produk, harga_modal, harga_jual, stok) VALUES (?, ?, ?, ?) """, produk)

    conn.commit()
    conn.close()
